{
    "metadata": {
        "kernelspec": {
            "name": "SQL",
            "display_name": "SQL",
            "language": "sql"
        },
        "language_info": {
            "name": "sql",
            "version": ""
        }
    },
    "nbformat_minor": 2,
    "nbformat": 4,
    "cells": [
        {
            "cell_type": "code",
            "source": [
                "\r\n",
                "create database Training_Batch2;\r\n",
                "use Training_Batch2\r\n",
                " create table Employee(id int, name varchar(23), department varchar(12),salary money)\r\n",
                " sp_help 'Employee'\r\n",
                "\r\n",
                " insert into Employee values(1,'Shivam','SDE',5679);\r\n",
                " insert into Employee values(2,'Aditya','SDE2',38967.33);\r\n",
                " insert into Employee values(3,'Shivam','SDE2',3967.43);\r\n",
                "\r\n",
                " insert into Employee values(4,'Satya','SDE3',4000.00),(5,'Rambhu','SDE',39000.00),(6,'Aniket','DT1',2500.00);\r\n",
                "\r\n",
                " insert into Employee(name,department) values('Sachin','SDE1')\r\n",
                "\r\n",
                " select name,department from dbo.Employee\r\n",
                " select * from dbo.Employee;\r\n",
                "\r\n",
                " create table Emp(id int identity (101,2), name nvarchar(23));\r\n",
                " insert into Emp values('Mayura'),('Rushikesh'),('Saurabh'),('Anurag');\r\n",
                " select * from dbo.Emp\r\n",
                "\r\n",
                "select id as EmployeeId, name as EmployeeName from dbo.Employee\r\n",
                "\r\n",
                "\r\n",
                "--where\r\n",
                "--order by\r\n",
                "--group\r\n",
                "\r\n",
                "select * from Employee where salary>4000;\r\n",
                "\r\n",
                "update Employee set department='SDE2' where id=1;\r\n",
                "update Employee set id=7,salary=3250 where name='sachin'\r\n",
                "\r\n",
                "select * into Emp1 from Employee where 1=2;\r\n",
                "select * from Emp1;\r\n",
                "\r\n",
                "select * into Emp2 from Emp1\r\n",
                "select * from Emp2\r\n",
                "\r\n",
                "delete from Emp2\r\n",
                "\r\n",
                "drop table Emp2\r\n",
                "\r\n",
                "select distinct department from Employee;\r\n",
                "\r\n",
                "select * from Employee where department in('SDE2','SDE1');\r\n",
                "select * from Employee where department not in('SDE2','SDE1');\r\n",
                "select * from Employee where salary between 4000 and 5000;\r\n",
                "select * from Employee where salary not between 4000 and 5000;\r\n",
                "select * from Employee\r\n",
                "\r\n",
                "select isnull(id,0) as id, name, isnull(department,'NoDept') as department, isnull(salary,0) as salary from Employee\r\n",
                "\r\n",
                "select * from Employee where department is null;\r\n",
                "\r\n",
                "alter table Employee add designation varchar(23);\r\n",
                "alter table Employee alter column designation varchar(45);\r\n",
                "alter table Employee drop column designation\r\n",
                "\r\n",
                "sp_rename 'Employee.department','designation'\r\n",
                "\r\n",
                "sp_renamedb Training_Batch2,EmpDB\r\n",
                "sp_renamedb EmpDB,Training_Batch2"
            ],
            "metadata": {
                "azdata_cell_guid": "57d6b210-0855-4a72-8e9c-2aaf1947a48f"
            },
            "outputs": [],
            "execution_count": null
        }
    ]
}